### ISSUE TITLE
[PROD] Displaying Local Unit Names

### ISSUE THREAD

**Issue by davidmuchatiza** [IFRCGo/go-web-app#911] opened 2024-05-02 10:10 UTC
Sure, here's a GitHub ticket based on the provided information:

**Description:**

Currently, the tooltip title for the Local Unit map is utilizing local names (`Name_LOC`). However, some local units only have English names (`Name_EN`) available, and no local names are provided. This leads to inconsistency in the display of names across different local units.

**Suggested Solution:**

To maintain consistency and improve user experience, I suggest implementing the following solution:
- Continue using local names (`Name_LOC`) where available.
- If the local name (`Name_LOC`) is blank for a particular local unit, display the English name (`Name_EN`) instead.

This approach ensures that users receive relevant information irrespective of the availability of local names.

**Priority:**

Medium

**Comment by samshara** [comment] 2024-05-02 11:53
@davidmuchatiza @szabozoltan69 Perhaps the most recent data hasn't been properly imported into both the staging and production environments. How can we confirm this?

**Comment by szabozoltan69** [comment] 2024-05-02 12:07
I fix the missing fields of the loader. (There are quite a lot.)
Sorry for the error, @samshara and @davidmuchatiza and team.
(The root cause was: the duplication and parallel maintenance 2 similar jobs: import-local-units-csv.py / import_local_units_health.py )

**Comment by szabozoltan69** [comment] 2024-05-02 12:16
Data fixed on Staging and Prod.
Fixed job is on GitHub.

**Closed as completed** 2024-11-27 09:19 UTC
Labels: TC, geo
