### ISSUE TITLE
PER - Missing notes from historical PER processes

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#459] opened 2024-01-12 08:18 UTC
Notes field is not populated in case of legacy data (created before the new PER launch). Data is available in the database, but it does not appear on the frontend.

Example:
•	Kenya RC
•	PER Cycle: 1
•	Link: https://go.ifrc.org/per-process/98/assessment
•	API link: https://goadmin.ifrc.org/api/v2/per-assessment/70

component IFRCGo/go-web-app#10, Business continuity, the text was "Business Continuity (BC) plans are triggered by needs; there is no standing BC plans. NS now has a BC plan for COVID-19 (for all levels) which also covers NS health facilitates/services, and this has been tested. In past one was developed for elections. It has not been developing a BC plan for floods. BC plan is led by HR with technical support from DM; approval is made by Head of HR/DSG. Normally, this is not an elaborated document. NS does not have pre-agreed/approved procedures to communicate with donors; this is done after an EW/ emergency." 

![image](https://github.com/IFRCGo/go-web-app/assets/68283148/4032516b-2754-4b0a-b615-db8efd238a24)

Data from the per_formdata table:
id                                       | 34643
notes                                    |
form_id                                  | 395
question_id                              | 74
selected_answer_id                       | 6
notes_ar                                 |
notes_en                                 | Business Continuity (BC) plans are triggered by needs; there is no standing BC plans. NS now has a BC plan for COVID-19 (for all levels) which also covers NS health facilitates/services, and this has been tested. In past one was developed for elections. It has not been developing a BC plan for floods. BC plan is led by HR with technical support from DM; approval is made by Head of HR/DSG. Normally, this is not an elaborated document. NS does not have pre-agreed/approved procedures to communicate with donors; this is done after an EW/ emergency.
notes_es                                 |
notes_fr                                 |
translation_module_original_language     | en
translation_module_skip_auto_translation | f

### Functional Requirements

- [ ] IFRCGo/go-api#2000

**Comment by szabozoltan69** [comment] 2024-01-12 08:40
The interesting is that the same form_id, but previous question_id has no issue, it appears fine, as it can be seen on the ^ screenshot. Though it is on 10.1, and 10.2 is an other text. And the simple **notes** field (so not the **notes_en**) is empty.
```
id                                       | 34641
notes                                    |
form_id                                  | 395
question_id                              | 73
selected_answer_id                       | 1
notes_ar                                 |
notes_en                                 | BC plans are triggered by needs; no standing BC. NS now has a BC plan for COVID-19 (for all levels) and this has been tested; in past one was developed for elections. Normally, this is not an elaborated document. NS has not been developing a BC plan for floods. BC plan is led by HR with technical support from DM; approval is made by Head of HR/DSG.
notes_es                                 |
notes_fr                                 |
translation_module_original_language     | en
translation_module_skip_auto_translation | f
``` 
So the issue is:
Why can't we find in the output of https://goadmin.ifrc.org/api/v2/per-assessment/70/ the 
```
"question": 74
```
text? (Only other "question": 7* ones are there.)

**Comment by szabozoltan69** [comment] 2024-01-12 10:15
Maybe we have a default limit of joined records, I mean:
```
SELECT ••• FROM "per_perassessment" LEFT OUTER JOIN "per_overview" ON 
("per_perassessment"."overview_id" = "per_overview"."id") 
WHERE "per_perassessment"."id" = 70 LIMIT 21
```

**Comment by samshara** [comment] 2024-01-16 08:54
### Functional Requirements
- [ ] Migrate old per notes data

**Comment by tovari** [comment] 2024-02-09 14:59
Checked by Belen on staging. Works well.

**Comment by samshara** [comment] 2024-02-20 05:21
@tovari , we have worked on a solution but it has not been deployed to staging. 

The PR is here https://github.com/IFRCGo/go-api/pull/1972

@szabozoltan69 did we implement anything that would have potentially fixed this on staging?

**Comment by steph-gm** [comment] 2024-02-26 16:49
Hello, revising on Staging, the **component 10** notes are now visible on the PER processes (I've checked Kenya RC, Democratic Republic of North Korea, Ghana). But the other component notes are still not visible.

For example, Democratic Republic of North Korea have notes on almost all components, but only the notes of component 10 are visible. Example of notes of the component #2:
"
     The NS does not have a specific DRM strategy. However, elements normally found in DRM strategy are 
    captured in their contingency plans, for example context analysis, target population and definition of sectors. 
    Additionally, the overall DM objective is reflected in the DM policy.
    ● Indicators to measure whether the NS is meeting operational objectives are missing from relevant operational 
    documents (e.g. contingency and response plans).
    ● Although there is no separate DRM strategy the elements usually found in a DRM strategy are captured in 
    other documents (e.g. CPs) and are well known by staff and volunteers.
    ● Staff from the different technical sectors and support services were included in the development of the CPs
    which are revised every 3 years
"

**Comment by udaynwa** [comment] 2024-02-27 03:18
@steph-gm thanks for the details, we will start looking into it.

**Comment by udaynwa** [comment] 2024-02-27 07:50
@steph-gm , we have pushed the fix to Staging. Can you please go ahead and verify them? 

cc @tovari @thenav56

**Comment by steph-gm** [comment] 2024-02-28 02:23
Hi @udaynwa , confirming it is working well now, all components notes/summaries are visible :)

**Closed as completed** 2024-05-03 13:04 UTC
Labels: type: bug, TC
