### ISSUE TITLE
[PROD] Surge Alerts different issues

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#472] opened 2024-01-12 10:18 UTC
- [x] [All alerts](https://go.ifrc.org/alerts/all)  are listed as open
- [x] There is something wrong with the filtering we are using to display the Alerts on the [Surge overview page](https://go.ifrc.org/surge/overview) I can see an open alert in the Moroco page that is not being shown in the general overview, see PrtSc: 
![image](https://github.com/IFRCGo/go-frontend/assets/69478743/7abf277a-c456-448e-ac1c-7dad1e5625f9)
- [x] The [Surge tab](https://go.ifrc.org/emergencies/6646/surge) on Emergency pages shows all alerts, not only Open alerts
- [x] If the user is navigating from an Emergency page and goes to All surge alerts, it should show only Alerts related to the emergency they were coming from.

@tovari anything I missed from our call?
@udaynwa @szabozoltan69 @batpad

**Comment by batpad** [comment] 2024-01-12 12:20
For the issues where it's showing more alerts than expected - i.e. alerts even after they are closed:

In the old site, we added a filter to the query to the backend to filter out surge alerts where the end_date had passed. The relevant portion of the code: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/alerts-table.js#L133

My hunch is this filter is not being applied in the re-write? cc @udaynwa @frozenhelium

**Comment by udaynwa** [comment] 2024-01-17 11:53
@anamariaescobar , a couple of comments
> [All alerts](https://go.ifrc.org/alerts/all) are listed as open

We could not replicate this one. If you go over to page 2, page 3, you should see Surge with status `Closed` and `Stood down` also. 

> There is something wrong with the filtering we are using to display the Alerts on the [Surge overview page](https://go.ifrc.org/surge/overview) I can see an open alert in the Moroco page that is not being shown in the general overview, see PrtSc:

[Surge Overview page](https://go.ifrc.org/surge/overview) has a condition that shows Surge within the last 30 days. Whereas for the [Emergency's Surge page](https://go.ifrc.org/emergencies/6646/surge), there is not such time restriction. That is why you can see an alert in the Emergency's Surge page, but not in the Surge Overview page. The condition was the same in the old GO. Can you confirm if this is the expected behavior? 

cc @batpad @tovari @frozenhelium

**Comment by anamariaescobar** [comment] 2024-01-17 13:48
@udaynwa,

- For the All Alerts part, you are right, there are a couple of closed and stood down, however if you go over to the page 14 (which still contains data from 2023, so after the conection with Molnix was done we get not only all Appeals Open, but also we are missing dates and all the keywords (labels) - I have requested the Surge team an export from Molnix with ALL ALERTS (at east from 2023), so I can compare it with what we have, but it seems that the issue goes beyond what we initially thought...we will revert back as soon as I get the export and can do some looking around - hopefully tomorrow
- For the second one, I believe that that condition was only for the Stood downs, but again, I will check with the Surge team and confirm on this one!

@batpad @tovari @frozenhelium @szabozoltan69

**Comment by batpad** [comment] 2024-01-18 06:45
@anamariaescobar -

I can identify two things here:

 - The table still shows the `Start Date` as `Immediately` even when an alert is closed. This is because the logic for showing `Immediately` is just if the Start Date is less than now, but we probably need to show something different if the Alert is already Closed as Start Date `Immediately` is misleading for a closed alert.
 - The other thing I'm seeing is that data from Molnix with a status of `archived` containing no data about start, end dates, etc. which is causing the missing dates, etc. For example: https://goadmin.ifrc.org/en/admin/notifications/surgealert/18410/change/?_changelist_filters=q%3DSamoa%2BEarthquake
 
I'm not sure what the idea behind these `archived` items from Molnix are? Do they contain the dates data in Molnix? If not, should we just be ignoring `archived` items from Molnix?

Am pretty sure this issue is primarily with `archived` items from Molnix not containing start and end dates. But happy to look closer as well.

**Comment by anamariaescobar** [comment] 2024-01-26 09:44
Hello all!!!
The second item in this ticket will be resolve if we implement a solution for #481 

@udaynwa @tovari @batpad @frozenhelium @szabozoltan69

**Closed as completed** 2024-09-13 13:11 UTC
Labels: type: bug
